### ISSUE TITLE
Images for first time slide

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#1035]
There are three blank spaces for images in the first time slide mockup, but no images.

**Comment by fzzzy** [comment]
Ping, can you work on this soon?

Also, can you create an asset to use as the arrow that points at the shot button?

**Comment by brampitoyo** [comment]
I think we can do a simple and elegant instruction using the famous picture from Mozilla Summit 2010.

![pageshot tour](https://cloud.githubusercontent.com/assets/51007/13834130/4d243f3e-ec51-11e5-9f71-20c0b3f72168.png)

We can use the yellow bar (which has an arrow on top of it) to point at the shot button.

Thoughts?

**Comment by brampitoyo** [comment]
Original image below:

![mozilla-summit-2010](https://cloud.githubusercontent.com/assets/51007/13834157/823160bc-ec51-11e5-8ef8-f0f7dadf7af0.jpg)

**Comment by ianb** [comment]
We might want to punt on this part:

![image](https://cloud.githubusercontent.com/assets/44390/15163611/0d8c6150-16cf-11e6-942f-787a050349c9.png)

Just because attaching to the position of a button is somewhat more complicated (using UITour or some other interface), and we could just refer to the button instead (at least as a first step).
