### ISSUE TITLE
Responsive design for shot page

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#1049]
There are some design specs in #992

**Comment by pdehaan** [comment]
Also this seems partially related:

![mozilla-services_pageshot](https://cloud.githubusercontent.com/assets/557895/18331953/8934aaf0-7517-11e6-98c7-e068ed718fc5.png)

**Comment by ianb** [comment]
We should kill the "Updated" message entirely.  The light gray is the "end" of the page.  Maybe we need something like `html {min-height: 100%}` ?  I think 93f80467e8cf8080050183cdd556b1218b683bd2 is the commit that regressed this.

**Comment by pdehaan** [comment]
Oh, I thought that "Updated" message was somehow specific to my shot. Yeah, showing a server deploy date seems awful[ly unnecessary]. For anybody interested (usually only QA), you can get that via https://pageshot.dev.mozaws.net/__version__#commit anyways.

We'll still need to address this though, since you can easily get the "Send Feedback" text to overlap, and I don't see any specific "Feedback" guidance in #992 mockups.

**Comment by fzzzy** [comment]
The "expires" ui still wraps incorrectly, so there's more work to be done here.

**Comment by ianb** [comment]
Duplicate of #1792
