### ISSUE TITLE
Design "this page is a copy" indicator

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1143]
Something so that people understand it's not a framed page, but a copy of the page.

**Comment by brampitoyo** [comment]
A few possible solutions:

![copy-indicator-i01](https://cloud.githubusercontent.com/assets/51007/14840008/f33fb608-0c83-11e6-96e3-2cbc85469989.png)
![copy-indicator-i02](https://cloud.githubusercontent.com/assets/51007/14840013/fa23e39a-0c83-11e6-8bd0-2d07983cea54.png)
![copy-indicator-i03](https://cloud.githubusercontent.com/assets/51007/14840016/0154f424-0c84-11e6-8b03-3f647ee3d9ca.png)
![copy-indicator-i04](https://cloud.githubusercontent.com/assets/51007/14840017/061a7eca-0c84-11e6-92bc-49b6b8c80693.png)
![copy-indicator-i05](https://cloud.githubusercontent.com/assets/51007/14840021/0baf72f0-0c84-11e6-8f1c-fad4dacbc80b.png)

I like the last solution the best. It’s the least intrusive.

**Comment by ianb** [comment]
Google News is a good example page, because it's busy and it's hard for me to see most of these!  Something about the full-width bar in particular feels like it blends into the page layout.

Is there a way that the "copy" tag could break out of the content area, but also cover the content area?  I think that would help emphasize that it's an annotation of the page, not the page itself; and by having it over the content it would emphasize that it's about the content, not just metadata.

In some sense the last one does that best for me: it doesn't fit into the page layout, and so my eye doesn't skim over it in the same way.  Though the second to last one also has potential, though I'd rather have it more prominently in the top-right corner.

**Comment by brampitoyo** [comment]
I agree. The full-width bar isn’t only intrusive when seen. It also tends to disappear once you get used to it!

The best solution seems to be something that appears on the corner of the page, but when you scroll down further, it continues to ‘stick’ to the header area. In other words, `position: fixed`.

The second to last solution has an obvious benefit that the other ones don’t have: it’s rotated 45º. Because it looks out of place compared to every other website element under it, it won’t be skipped over so easily. But at the same time, since you read from left to right, your eye almost always starts out on the left side of the page. This means that any element that’s positioned on the right corner won’t block your view immediately. It’s just a gentle reminder.

One fault I noticed about my design is that the size is far too small, and the yellow might not look noticeable enough.

So I’ve tried to address those problems here: http://codepen.io/brampitoyo/pen/wGYWgE

What do you think?

**Comment by ianb** [comment]
That codepen link doesn't work for me (just gives a blank page)

**Comment by brampitoyo** [comment]
Sorry about that. It works on my computer, and looks like this:

![screen shot 2016-05-03 at 17 30 22](https://cloud.githubusercontent.com/assets/51007/14975335/c7eaa956-1154-11e6-86cd-ea9a14f15369.PNG)

**Comment by ianb** [comment]
We'll go with the codepen example, with `pointer-events: none`
