### ISSUE TITLE
PageShot button on about:newtab should open My Shots

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1167]
Right now Chrome about pages aren't supported at all.  Which is fine, but then you can't get to the My Shots button.

**Comment by brampitoyo** [comment]
One thing we can do when PageShot is opened on `about:blank`, `about:home` or `about:newtab` is something like this:

![pageshot about home](https://cloud.githubusercontent.com/assets/51007/15173351/b12dcfc0-17af-11e6-9ffe-77f717e20630.png)

Notice how the instruction changes, the “Save” button has disappeared, and there’s no crosshair.

We should make sure, though, that PageShot cannot be invoked when you’re at any other `about:` pages (like `about:preferences`, for example) because it will be confusing to users.

**Comment by ianb** [comment]
Note that Pocket immediately opens getpocket.com when you invoke it on a new tab page.  (Though I'll note I never knew this, despite being a long-time Pocket user, so it's not very discoverable)

**Comment by ianb** [comment]
Increasing this in priority because I personally hit this a lot, because going to My Shots by opening a new tab and clicking the PageShot button is just very natural.
