### ISSUE TITLE
Think about use cases for saving the whole page in code/DOM

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#1214]
I had a chance to talk and demo PageShot to @TLHuang earlier today.

She asked me “Why would I save the whole page in code, instead of just saving the whole page as an image?”

My answer was:
- If your interest is only to archive a page at a moment in time, a full-page, top-to-bottom image of the page sounds more familiar
- If your interest is to archive and then return to the page to read it later, code/DOM is better

I suppose we haven’t articulated exactly _why_ saving the code/DOM is better in user language. We know you can select text, save image, etc. That sounds like a list of feature to me. But a user can simply save a screenshot of the paragraph or the sentence, and she can screenshot the image on the page.

I’m hoping that we can come up with some strong user benefits towards saving the code/DOM in this issue.

**Comment by fzzzy** [comment]
I think having the text of the page be searchable and copyable is the biggest benefit, but as usual, explaining the benefit of the dom copy versus an image copy is hard. Being able to increase or decrease the font size is another benefit.

People seem to be getting used to images of text (because of twitter?) but I think this is a horrible development that I hope does not continue. I guess images of text also sidestep issues with fonts, perhaps especially with languages that use non-roman characters, which could be a benefit. I would hope that unicode and unicode fonts included by default are getting good enough that this isn't as big of a problem as it used to be.

**Comment by ianb** [comment]
Here are some cases where the DOM capture is better:

* Something with a lot of textual information that you want to save:
  - A receipt or invoice
* Something with outbound links that you might want to preserve:
  - A thread where people discuss things with outbound links
* Capturing content to share with someone who doesn't have the original page
  - Sharing benefits information from mana.mozilla.org
* A case where you expect the content to change or disappear:
  - A peculiar algorithm-generated combination of stories
  - A candidate political policy page
  - Something you are about to report for abuse

For a combination of clip+page, you might want:
* To highlight or remember some part, while *also* having access to the links or other metadata
* To remember a quote or item
* To bookmark or make note of some important item embedded in a much larger document (e.g., a specific comment when there aren't permalinks)
