### ISSUE TITLE
Set up a new tech stack

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#125]
We discussed what libraries we want to use as we move off appengine to plain node, and we came up with this list to try:

sass scss
gulp
6to5
browserify
react
hapi
Postgres/MySQL (no ORM)

I am going to create a small toy project with this stack to see how it feels.

**Comment by ianb** [comment]
String template version of SQL escaping: http://ivc.com/blog/better-sql-strings-in-node-js/

It refers to io.js, but would apply to us with 6to5 too.

**Comment by fzzzy** [comment]
Yes, we should certainly investigate using es6 template strings for generating sql queries. It would be better to use a library that someone else already wrote.

Also, we should absolutely use generators to straighten out control flow. I have written a few libraries for javascript that have actor semantics (mailbox, cast) but jlongster recommended https://github.com/ubolonton/js-csp so I'd like to try that.

**Comment by ianb** [comment]
I'm open to checking it out and experimenting, but I'm reluctant to add major code rewriters – specifically things that change the call stack and basic structure of functions.  Though maybe the "csp" in js-csp isn't the csp I expected.  Though to use generators I'm assuming we'll see the function get rewritten significantly?

But I'd rather we do stuff that's a little awkward and conventional than unusual and elegant.  At least with 6to5 we're jumping on a bandwagon that presumably everyone will eventually join, even if not every feature seems worth it (e.g., tail calls).  Promises are also a conservative enough choice, even though they are no panacea.  

On the client I find a lot of the code will be event-based (i.e., addEventListener), which is neither here nor there.  Or, for instance, network requests on the client are probably best handled by fairly general code – no one codepath usually has a good way to deal with network errors, instead at best we expose the error somehow to the user, or do a retry, or something fairly generic.  I would like us to find the pain points before we try to fix them with more tooling.

**Comment by fzzzy** [comment]
I wouldn't say using generators as green threads is unusual at this point. It's even in the python standard library, written by guido himself as tulip. task.js has been around for about 5 years, I think (http://taskjs.org/). I first implemented generators as green threads for twisted in 2002.

Generators are the part that requires a code rewriter. 6to5 uses Regenerator for this, a Facebook project. Generators are easy to rewrite because they aren't true coroutines. A generator can only switch to it's calling frame.

A generator like this:

function* foo() {
  yield "foo";
  yield "bar";
}

Gets rewritten to something like this:

function foo(resume_point) {
  switch(resume_point) {
    case 1:
      return "foo";
    case 2:
      return "bar";
  }
}

This is oversimplified pseudocode, but the point is generators are much easier to implement than real coroutines or continuations, which is why they are slowly winning the war over time.

**Comment by ianb** [comment]
If we have at least some code written conventionally I think we can look at what this will actually do.  For instance, on the server we'll have to interact with lots of libraries written with Node-style callbacks.  What will that look like using coroutines?  Will we mostly just be doing a couple database requests and rendering a template?  With working code in hand we can figure out what we'd gain with other control flow techniques.

**Comment by fzzzy** [comment]
Yes, I don't think it's worth including js-csp in the stack until we have some real code and it's obvious that it would make things cleaner.

With coroutines, every time you have a promise you want to wait for or need to wait for a callback, you just yield a wrapper object around the promise or callback, and the generator is resumed when the callback is called or the promise is resolved.

**Comment by fzzzy** [comment]
(Terminology got a little sloppy in the comments here; it's not possible to implement coroutines using generators, because real coroutines can switch to any other coroutine. A generator can only switch to the parent frame. Some people have started calling libraries that switch control flow using generators semicoroutines. I often refer to them as green threads.)

**Comment by ianb** [comment]
Now that I'm thinking about servers, some more of the stack (not necessarily for local development):

- Maybe [Circus](http://circus.readthedocs.org/en/0.11.1/) for managing processes.  Or some Node-specific thing, but since Circus is developed in our group... (there's also [supervisord](http://supervisord.org/) and some other common tools in the category)
- I'm thinking that we might get the most bang out of our ops buck (which we are paying out of our dev wallet) if we make it easy to host multiple instances/versions on the same machine.  Then we don't have to figure out spinning up machines and automating all that.  But to do that we have to route requests through port 80 to multiple Node instances.  nginx?  I guess it [works with websockets](http://nginx.com/blog/websocket-nginx/) now.
- We should do something with logs.  I'd like to get alerts about errors if possible.  I'm very open to using a third party service.  We could go the whole [Heka](http://hekad.readthedocs.org/) path, but it feels like a bit much for now.  But maybe...
- We should do some basic stats, maybe Google Analytics.  We have a private Mozilla account for this.  (#30 is a ticket for better metrics, but I think Google Analytics might be worth having too, or worth starting with)
- I'm assuming the Node server will be very self-contained.  That is, it will depend as little as possible on the system – directory-local install, as few dependencies as possible (probably the DB driver, ideally nothing else?)
- We might want to think about managing the database schema.  @chilts has some tools he's made for Firefox Accounts that could relate.  But since we aren't expecting to use any kind of ORM, we can use really any schema management tool, there's no language dependency.  Could be [overthought](http://www.liquibase.org/) (XML!)
- We will want smoke tests before very long.  I'd like to do semi-continuous-deployment, and we should do some kind of basic health check after each deployment.  (We don't need automated rollback yet, we should just be self-aware when we break something.)  Since these are end-to-end functional tests we have quite a bit of flexibility about what to use.  Authentication gets trickier.  @st3fan also has some tools for this (being used with FxA specifically, I think).  We could also make a testing authentication backdoor.  (I.e., identify a kind of scratch user who doesn't need normal authentication, and whose data is regularly wiped.)

It's a big list, we shouldn't do all of them at once!

**Comment by fzzzy** [comment]
I'm for Circus and Nginx.

Chronicle is using mozlog which is compatible with Heka.

I'm for Google Analytics.

Chronicle is now using Postgres instead of MySQL, and recommended node-postgres and pg-patcher.

Not sure what to use for tests. Chronicle is using The Intern, and I have used Mocha, Istanbul (for generating coverage reports) and Selenium Webdriver on another project.

**Comment by ianb** [comment]
[mapleTree](https://github.com/saambarati/mapleTree) looks okay for routing.

**Comment by kitcambridge** [comment]
Check out [routes](https://www.npmjs.com/package/routes) and [router](https://www.npmjs.com/package/router), too. routes is more like mapleTree; router is inspired by Express.

**Comment by kitcambridge** [comment]
I just stumbled across [Routr](https://github.com/yahoo/routr)—you mentioned you're more interested in a builder than a dispatcher; looks like this fits the bill.

**Comment by fzzzy** [comment]
This has been merged
