### ISSUE TITLE
Check out Wayfinder

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#131]
[Wayfinder.is](http://wayfinder.is/)

**Comment by brampitoyo** [comment]
I like Wayfinder’s idea of stitching link together to create some sort of a story. In essence, it’s turning a list of links inside a folder into a narrative. One of the PageShot features we’ve talked about is excerpts.

* A link can have many excerpts.
* User can PageShot many links.
* We have a lot of excerpts and a lot of links. What can we do with them?

I think one thing we should investigate is whether it would be interesting to string together highlighted excerpts from various collected articles to create a story. I’m not convinced that this is a good idea. But it’s been done very successfully by newspapers.

Look at a front-page news piece. You’ll notice that every sentence is literally a quote from somewhere else. With PageShot, you can do the same. You can take one interesting bit from this link and combine it with another interesting bit from that link to create potentially interesting new reading.

It’s a bit disjointed, like reading a book full of quotes. But it’s also full of ideas that comes from many places. As a reader, you can always check the source because PageShot keeps track of where each excerpt came from. We can even display the preceding sentence or paragraph of that excerpt, so you always know the context.

##### One article
* One article can have many highlighted excerpts
* User can pick between reading/sharing the full article, or just the highlighted excerpts

#### Multiple articles
* First of all, there needs to be a view that collects excerpts from all the articles user have collected
* Then, these excerpts can be shuffled and combined together in order to make a coherent point

**Comment by ianb** [comment]
Copied to [gdocs](https://docs.google.com/document/d/1OYqD5K64SxbxR8YLBk4OEi2rYL4N9n60KbsbmlQjHus/edit#)
