### ISSUE TITLE
Clean up Share thing on the shot detail page

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/pageshot#1463]
- [ ] overall tidying
- [ ] get rid social shares. we can comment these out for not but they are not effective. The URL is the thing. cf [this article] (http://www.adweek.com/socialtimes/report-moovweb-social-share-buttons/620045)

**Comment by fzzzy** [comment]
I'd suggest getting rid of the "mailto" email share entirely. Very few people have a local email client configured nowadays.

**Comment by ianb** [comment]
One purpose of the share interface generally is to push the concept of sharing, in the guise of making sharing "easier".  It also gives us some concept of networks which we wouldn't otherwise have (though obviously biased for the networks that are used by people that fine sharing buttons useful).

mailto doesn't work that well, but we *could* make it work much better than a link.  Having people try the mailto experience (even if it sucks) would be an indication that it could be worth developing further.
