### ISSUE TITLE
Clear search results when form clears

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/pageshot#1464]
## current

hitting delete doesn't clear search results, i have to hit the search button

## expected

clearing a search via keystroke will return unfiltered results

**Comment by johngruen** [comment]
@fzzzy this is less drastic, but also maybe the most important piece.

**Comment by fzzzy** [comment]
@johngruen I agree with you that these are important, so we should probably talk about moving to another full text indexing solution.

**Comment by johngruen** [comment]
@fzzzy i'm content to do just this for launch becasue right now it feels broken. Let's talk about search improvements in our meeting today

**Comment by ianb** [comment]
@johngruen : I don't understand the bug here.  If I search for something locally, and it returns results, and then I erase the search string and hit enter (or hit the `=>` button) then I get all the items.

Do you want it to show all the items before you hit enter?  I.e., when you delete the search string it immediately resets to all items?

**Comment by johngruen** [comment]
in my dreams, i hit delete in the field and it automatically shows the all my shots again w/o hitting enter

**Comment by ianb** [comment]
OK, that's doable, just needed to clarify
