### ISSUE TITLE
Run some page speed test on a shot page

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1557]
We should run some page speed test on the shot page, just to see what we get.  (Work identified should probably be triaged.)

**Comment by ianb** [comment]
Some notes [from just the hompage](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fpageshot.net&tab=mobile):

* [ ] https://pageshot.net/ga-activation.js should have an expiration, and should have a cache-bust when it's referenced
* [ ] We should test if ga-activation can be an async script (maybe not)
* [ ] Try minimizing our bundles

From analyzing a [shot page](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fpageshot.net%2FmtT1LqaTutIsSc8M%2Fwww.spacex.com):

* [ ] core.js is not included in the bundles, makes for a separate request
* [ ] server-bundle.js could probably be async?
* [ ] configure-raven is yet another script; combine, or make async?
* [ ] ditto set-content-hosting-origin.js
* [ ] maybe parent-helper can go in as part of the bundle
* [ ] All the non-bundle scripts could include a git revision and expiration time
* [ ] The PNGs we create could be better optimized

It also showed the mobile view with the header getting pretty crushed:

![image](https://cloud.githubusercontent.com/assets/44390/18889128/14813976-84c1-11e6-9032-75f70a9f9886.png)

**Comment by peterbe** [comment]
The [frame.css](https://pageshot.net/static/css/frame.css?rev=3301041) file isn't optimized. Saving a few bytes on removing it's white space is probably no big time saver. But considering how little it is, I would recommend inlining the CSS. If you don't want to allow inline style tags, due to CSP, you can generate it with a nonce in some build step. That means the browser doesn't need to make a network roundtrip to start rendering.

**Comment by ianb** [comment]
The optimizations we're planning on making soon (along with ticket numbers) are listed in this comment: https://github.com/mozilla-services/pageshot/issues/1624#issuecomment-255158499

We should re-test after those optimizations.
