### ISSUE TITLE
Shot error door hanger scrolls horizontally

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1567]
![mozilla_firefox](https://cloud.githubusercontent.com/assets/557895/18686625/69727db8-7f31-11e6-8858-d47f40f049e1.png)

I clumsily did something, and noticed a horizontal scrollbar and it looks a bit "weird".

![menubar_and_install_page_shot_and_summary_card_with_large_image___twitter_developers_and_1__npm_run_firefox_--_-s_src__node__and_add-ons_manager](https://cloud.githubusercontent.com/assets/557895/18686608/58ea533a-7f31-11e6-920b-cc0508914a81.png)

Also, why prevent me from taking a screenshot of a shots page? It's a bit meta, but wonder if it'd be a very common use case for somebody who just installed the add-on (take a shot of the current page)... Although possibly moot if users install primarily via Test Pilot.

**Comment by ianb** [comment]
We put in the specific exception because @johngruen found himself accidentally doing this and creating strange results, and I think we might have seen users doing it in testing too?  User testing did specifically show people doing this with the My Shots page.  Generally it seems like a sign you are confused rather than trying to shoot a shot page.

@johngruen was planning on looking at the error panel styles.

**Comment by ianb** [comment]
Fixed in #1582
