### ISSUE TITLE
A few unused package.json dependencies

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1601]
### Found in:

```sh
$ git rev-parse --short HEAD # 3301041
```

### Steps to reproduce:

```sh
$ depcheck --ignore-dirs=build --ignores=babel-*,browserify,jpm,nodemon,node-sass,raven-js

Unused dependencies
* core-js
* mime-types

Unused devDependencies
* fs-promise
* fx-runner
* geckodriver
```

**Comment by fzzzy** [comment]
I think core-js is actually used, it is just linked to as a file on the filesystem. Ian just opened another bug to bundle core-js with everything else by using require on it, instead of linking directly to the file.

The geckodriver dependency automagically installs a binary named "geckodriver" I think? I'm not actually sure if we need that or not.

I think the others are unused.

**Comment by pdehaan** [comment]
Re: core-js,

Correct, sir!

```sh
$ git grep core-js
```

> 1. Makefile: `core_js_location = $(shell node -e 'console.log(require.resolve("core-js/client/core"))')`
> 1. package.json:    `"core-js": "2.4.1",`
> 1. server/src/views/frame.js:      `<script src={ this.props.staticLink("vendor/core.js") } key="core-js-js" />,`

**Comment by ianb** [comment]
I think that leaves `mime-types` and `fs-promise` to be removed

fx-runner is probably used by Travis?
