### ISSUE TITLE
Allow simple annotations with text and arrows to highlight something on a screenshot

### ISSUE THREAD

**Issue by jnachtigall** [mozilla-services/pageshot#1616]
ATM I use greenshot (Windows) or shutter (Ubuntu). Pageshot could greatly ease my workflow if it had some simple way of annotating screenshots. I think just being able to draw some red/green arrows and text on a scrreenshot before sharing it would be fine.

Most screenshots I do are for bug reports. So it is necessary to highlight/annotate something on a shot page.

**Comment by ianb** [comment]
@jnachtigall : do you find you need to include any text with the annotations, or are they self-explanatory?  Also, if the annotations were overlaid on the image but weren't part of the image, would that work?  That is, would you share the entire page, or just the image?  For example, [this](https://pageshot.net/Naac42q0QTTGLdcX/github.com) is the entire page, and [this](https://pageshot.net/images/757485fe-9968-4561-a396-12b028451073) is the image alone.

**Comment by jnachtigall** [comment]
@ianb 
> do you find you need to include any text with the annotations, or are they self-explanatory? 

I always add some small text if it's not self-explaining. Sometime also just a letter/number marker which I then explain in some other text outside the image (in a mail, or in the bug text). For an example, see the screenshots of this bug report in https://bugzilla.mozilla.org/show_bug.cgi?id=1296271 
* https://bug1296271.bmoattachments.org/attachment.cgi?id=8782429
* https://bug1296271.bmoattachments.org/attachment.cgi?id=8793676

> Also, if the annotations were overlaid on the image but weren't part of the image, would that work? That is, would you share the entire page, or just the image? For example, this is the entire page, and this is the image alone.

Probably it would be even better (and I guess easier to implement) if the text/annotations would be overlaid on the image page. So that one would need to share the page (and not just the image).

The fact that screenshot tools print annotations directly into the png/jpg image (which also makes it impossible to re-edit it later) is probably because they do not have a sensible way of doing it any better.

**Comment by ianb** [comment]
Also requested [here](https://discourse.mozilla-community.org/t/feature-request-basic-editing-drawing-tools/11181)

**Comment by Web4Guru** [comment]
Ianb linked my similar request from the discourse forums.  Yes, I would also like simple annotations.

I mostly draw a box around something or a line underneath something to highlight it.  I usually include text outside of the image.

As it is now, I would be sharing just the image, not the page.  So I actually would prefer the annotations to be added as part of the image instead of overlaid on the page.

However, I can see the use of having the original image without annotations, as well as benefits to using overlays in general (thinking about other possibilities).  Maybe store the original image as one shot and the annotated image as another shot? Possibly allowing multiple annotations of the same image?

I could see a use when you have a single screenshot of a list of actions to take, and then creating different annotations that highlight specific items at different stages as the actions are performed.

**Comment by jjnilton** [comment]
Pixelate/blur tool could be good to hide some private information when sharing the screenshot, when it's not possible keep it from the selected area.

**Comment by ianb** [comment]
We're tracking the design of this in #1849, I copied a couple notes and references this ticket from that one.
