### ISSUE TITLE
No new tab upon save?

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/pageshot#1653]
Kinda in line with my whining in https://github.com/mozilla-services/pageshot/issues/1627

When I take a screenshot, I don't feel like I need to see it on its permalink page. I take the screenshot for the sake of sharing it. 

How about something like this,
1) I click the Page Shot icon in the tool bar
2) I drag and select an area
3) I click the Save button
4) Almost immediately the little "share widget" pops up near the Page Shot toolbar icon. Ideally with a cheerful text like "Page Shot saved and ready to share!". But I'm still on the page I was on. Something like this: 
<img width="2107" alt="screen shot 2016-09-30 at 9 05 20 am" src="https://cloud.githubusercontent.com/assets/26739/18992657/94375a64-86ed-11e6-873e-8841c11f8a54.png">
But you have to imagine that the drag mode is cancelled. 

This way it doesn't have to open a new tab and take me to it just so I can use the little pop-up to get to the permalink URL.

**Comment by ianb** [comment]
One positive result we've gotten from user testing is that it's super-obvious to everyone that their clip was uploaded to a specific URL.  So they know it's cloud-hosted, that it's been successfully uploaded, they know what someone else will see if they share the URL, and the way the URL looks seems to be enough that people understand the sharing model (i.e., knowing the URL means having access to the shot).  So that new tab is doing a lot of heavy lifting, I don't think we want to replace it.

This is really just an aside, but since I'm thinking about this: It might be too weird, but we *could* have tab management features in My Shots.  Like, show which shots are open already, focus the opened tab instead of opening a new one when that's possible, and there could be a "close all Page Shot tabs" feature to do cleanup.  But I doubt that would address your particular concern.
