### ISSUE TITLE
Does not work, always shows error message

### ISSUE THREAD

**Issue by rugk** [mozilla-services/pageshot#1683]
![shoterror](https://cloud.githubusercontent.com/assets/11966684/19057389/cdd4ebe4-89cf-11e6-8405-1ef4bc4b4f89.gif)

In the console there is no useful error message. Mostly it is just a small CSP error: 
>Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://pageshot.net https://www.google-analytics.com 'nonce-c11b06a8-cc7e-440f-b977-2b48c739dc55'").github.com:1
>"Download the React DevTools for a better development experience: https://fb.me/react-devtools"

This error might be caused by some add-on, so i doubt this is causing the issue.

BTW: Note that I use NoScript, but it is whitelisted for all HTTPS sites.

Firefox 49
Linux x64 (Debian Jessie)

**Comment by SoftVision-CosminMuntean** [comment]
I can also reproduce this issue using the latest Page Shot add-on (v. 0.1.201610031844). And its not related to any add-ons since I can reproduce it on a clean profile.

[Affected versions]:
- Firefox 49.0.1 and up

[Affected Platforms]:
- Windows All
- Linux All

[Steps to reproduce]:
1. Open the browser and Install the Page Shot add-on.
2. Clear all cookies from History (Ctrl + Shift + DEL)
3. Navigate to any web page and click on "Page Shot" toolbar button.
4. Perform a selection and choose to save it.
5. Observe the browser behavior.

[Actual results]:
- The "Page Shot is out of order" error is displayed.

[Expected results]:
- The selection is correctly saved as a screenshot.

[Notes]:
- If you press the "My Shots" button form the doorhanger, you are redirected to: "https://pageshot.net/?pageshot-not-installed".
- If you restart the browser, Page Shot add-on will work as expected.
- Here are some console errors observed while trying to save a selection: https://goo.gl/FbN0Ds.
- @ianb  I think this might be related to #1673.

**Comment by rugk** [comment]
Thanks for the hint to https://github.com/mozilla-services/pageshot/issues/1673. Indeed I have third-party cookies disabled and I also [a cookie destroying add-on](https://addons.mozilla.org/de/firefox/addon/self-destructing-cookies).

**Comment by ianb** [comment]
I'm pretty sure the fix for #1704 will address this issue.  After applying that commit I can start Page Shot, delete my Page Shot cookies, and then successfully save a shot.

**Comment by rugk** [comment]
It works now. I don't know whether it is because of an update.

Only thing that changed: Uninstalled Adblock Plus, installed uBlock.
