### ISSUE TITLE
Create Changelog

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1702]
We should have a linkable changelog

**Comment by pdehaan** [comment]
We could maybe use [**conventional-changelog-cli**](http://npm.im/conventional-changelog-cli).

```diff
diff --git a/package.json b/package.json
index 6ccbe65..6f61d33 100644
--- a/package.json
+++ b/package.json
@@ -45,6 +45,7 @@
     "babel-preset-react": "6.11.1",
     "body-parser": "1.15.2",
     "browserify": "13.0.1",
+    "conventional-changelog-cli": "1.2.0",
     "eslint": "3.7.1",
     "eslint-plugin-react": "6.3.0",
     "fx-runner": "1.0.5",
@@ -64,6 +65,7 @@
     "url": "git+https://github.com/mozilla-services/pageshot.git"
   },
   "scripts": {
+    "changelog": "conventional-changelog -i CHANGELOG.md -s -r 0",
     "lint": "npm-run-all lint:*",
     "lint:addon": "make xpi && addons-linter ./build/*.xpi -o text",
     "lint:js": "eslint .",
```

Then running `npm run changelog`, I get the following CHANGELOG.md file: https://gist.github.com/pdehaan/ff532e19b96063102200915b21bce932

---

The results aren't _great_, because it looks like we only have one version/tag, so we'd need to make sure we bump the package.json version number on each milestone. Plus, we should make sure to squash commits so we can avoid 10 commits with the title of "WIP".
Conversely, we could start using a commit message convention (like Angular or whatever), where we use commit messages of "fix(addon): Do a thing with stuff" and conventional-changelog will only process commits with that particular format and ignore the rest.

**Comment by fzzzy** [comment]
@pdehaan We already use a commit message convention of "Fixes #XXXX" or "Fix #XXXX", so can we get conventional-changelog-cli to filter for that?

**Comment by ianb** [comment]
Thinking about this some, I think all I really would like is something that given a range dumps out some reasonable Markdown for all the commits, including links to individual issues, and ideally filtering out merge commits.  But then we should hand-edit the changelog from there, including putting in headers (`## Changed in v2` etc).

I'm thinking that during that we'll also split out user-visible changes from other stuff, and then use the user-visible section as the basis for a Discourse announcement.

**Comment by ianb** [comment]
After some discussion on IRC, let's just use conventional-changelog, except we'll post-process the changelog to link commits.

We can use this regex (in Python) to filter the output:

```python
import re
issue_regex = re.compile(r'#(\d+)')
def rewrite_issues(text):
    return re.sub(r'[#\1](https://github.com/mozilla-services/pageshot/issues/\1)', text)
if __name__ == "__main__":
    import sys
    sys.stdout.write(rewrite_issues(sys.stdin.read()))
```

That can also be embedded in a shell file/piped with `python -c`.
