### ISSUE TITLE
Not working on intranet URL's

### ISSUE THREAD

**Issue by richosr** [mozilla-services/pageshot#1716]
![sshotff](https://cloud.githubusercontent.com/assets/992654/19221374/6184e70e-8e6c-11e6-8bb9-dbdb504304f8.jpg)
When I try to screen shot on a local network url like 192.168.1.11/sitename/page.html, pageshot throws an error:

Page Shot went haywire.
Try again or take a shot on another page?
Failed assertion: Bad URL: 

It works fine on web based URL's.

regards
Steve

**Comment by johngruen** [comment]
This should be fixed in the latest release.

**Comment by ianb** [comment]
This should be fixed in the release, but many people haven't received the update (we are trying to understand why the update isn't going out).  This is the version you should have where this is fixed:

<img width="495" alt="image" src="https://cloud.githubusercontent.com/assets/44390/19322341/3c9bbb16-907e-11e6-9aa2-8c97867d5b79.png">

You can view this via **Tools > Add-ons** and go to Preferences under Page Shot.
