### ISSUE TITLE
use case: highlight and keep reading

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#172]
I'm reading [an article](https://www.pandastrike.com/posts/20150304-agile), and it says something clever (There's a reason we write code onto screens, rather than transmitting it as oral history like an epic poem). Ah! Now I know I want to share this post, but I haven't even read it yet.

I want to be able to select that quote, maybe switch to PageShot, but still keep reading. And I don't want my reading interrupted.

**Comment by brampitoyo** [comment]
What do you think about a behaviour like this?

**Saving a selection**

* If the PageShot button is activated while an area of the page is selected (via click-drag of a mouse, or tap-hold-drag on a mobile device), that area of the page is automatically saved.
* The panel opens, displaying the area you just selected, saying that it’s been uploaded to PageShot and the link’s been copied.
* This link, which leads to the Highlights View, will be available for you after you’re done reading and want to share the link somewhere.
* Want to grab the link again? Click the PageShot button. The panel will open with the link displayed.

**Adding a selection**

This is where it gets problematic. What if there are multiple interesting areas you’d like to highlight?

Currently the PageShot panel only allows highlighting *one* item. If you’d like to highlight more, you have to go to PageShot and use the Select Tool.

It might be interesting to give users the ability to select more areas than the initial one, then saving it in the same PageShot Highlight View

The flow then becomes:
1. Sees interesting quote or image
2. Highlight
3. Click PageShot button
4. Continue reading
5. Repeat step 1

**Bigger implication**
Can we make PageShot’s Select Tool redundant by simply asking user to highlight an element of the page, instead of drawing a box? There’s a pros and cons to box. By highlighting, you can’t select adjacent element if it’s not put right next to each other in the HTML code. But highlighting does have less friction than drawing a box.

**Alternative**
Every time you select an area, a small “Save to PageShot” button appears, that does the same thing as clicking a button would. This is similar to how Medium’s comment feature work. It involves more technical trickery, and can be quite annoying to some users.

**Comment by ianb** [comment]
I think the text clip behavior now satisfies this use case.
