### ISSUE TITLE
autoSelect failures

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#183]
**Note: most interesting comment is at the bottom, about autoSelect problems**

Right now in some cases when the autoSelect()'r can't figure out a smaller-than-the-page range, it just takes a shot of the whole screen  This is somewhat distinct from the screenshot, it's full resolution and shows up as a clip.

You can resize this selection, but it's awkward because the handles are right at the edge.

I'm wondering if we should just not do an auto-select if we can't come up with a reasonable range.

**Comment by brampitoyo** [comment]
There are a few possible behaviours:

* Make selection box 10–15% smaller than the whole screen
* Make selection box a default size that’s easy to resize (320x240?), then place it on absolute position a set distance from the top-left corner of the page (75 px down and 75 px to the right?)
* Choose one element of the page that’s sufficiently big enough, then make selection box the size of that element

Either way, we should not assume that the auto-selected area is the area the user wants to snap. Maybe in this case it would be nice to have a “Save” button appear besides the selection box? We only take a screenshot when user says so.

**Comment by ianb** [comment]
[Here](http://marc.info/?l=openbsd-tech&m=142655686417434) is an example of a page where we are taking a full screen, though maybe unfair because it's mostly one big `<pre>` tag

**Comment by brampitoyo** [comment]
I tested the example page (as well as [other](http://c2.com) [pages](http://www.math.leidenuniv.nl/~edix/) [like](http://www.tkm.uni-karlsruhe.de/~mirlin/) [it](https://people.math.ethz.ch/~embrecht/)) and saw that Pageshot took a selection box the size of the screen, then reduced it by a bit. This is the behaviour I wanted. I was able to select the handle because it doesn’t sit right at the edges of the page.

But it doesn’t work on [this page](http://wwwis.win.tue.nl/~debra/), even though it has a similar layout to all the others. Any idea why?

**Comment by ianb** [comment]
Personal homepages on universities are the weirdest.  That last page is set with `<div style="display: inline">` and autoSelect only looks in block level elements (not inline).  The page is baffling all around, so we won't be able to do better than fullscreen on it.

The rest are successful autoSelect cases, for the most part.  The pages are just laid out to be very wide, but they really are filled with content.  Only in that last one is it doing the fallback.

**Comment by brampitoyo** [comment]
I ran some autoSelect tests on popular English and Chinese-language sites.

#### Observations

* There are still plenty of situations where handles appear right on the edges of the page
* When handles did appear ‘edgy’, they’re often on one or two sides rather than all four. This makes resizing trickier than usual but not totally impossible
* On one instance (Yahoo home page), the handle overshoots so far to the side so it couldn’t be found
* On one instance (eBay home page), autoSelect completely failed to snap anything useful

#### Results

* Amazon
  * [Home page](https://cloud.githubusercontent.com/assets/51007/6794871/ddc49dde-d23c-11e4-85d7-c6d2e99fe381.PNG): needs fix, edgy handles on left and right
  * [Product page](https://cloud.githubusercontent.com/assets/51007/6794877/f42a71f2-d23c-11e4-9038-32ad1ee82bab.PNG): works
* eBay
  * [Home page](https://cloud.githubusercontent.com/assets/51007/6794888/103746ae-d23d-11e4-8ecd-b93cb5e3d639.PNG): failed, snapped random thin horizontal area
  * [Category page](https://cloud.githubusercontent.com/assets/51007/6794904/39895646-d23d-11e4-874f-70a34ee06ab0.PNG): works
  * [Product page](https://cloud.githubusercontent.com/assets/51007/6794906/4c2e3fa0-d23d-11e4-8c6c-4dcb494d40a2.PNG): needs fix, edgy handles on every side
* Facebook
  * [Wall](https://cloud.githubusercontent.com/assets/51007/6794921/7f126748-d23d-11e4-9665-6aeefe645ab0.PNG): needs fix, edgy handles on top
* Google
  * [Home page](https://cloud.githubusercontent.com/assets/51007/6794924/8f66fac8-d23d-11e4-88bb-9ec3ab30420d.PNG): needs fix, edgy handles on right and bottom
  * [Search results page](https://cloud.githubusercontent.com/assets/51007/6794925/90861c72-d23d-11e4-8e89-878b5400c733.PNG): needs fix, edgy handles on left and right
* NYTimes
  * [Home page](https://cloud.githubusercontent.com/assets/51007/6794961/2aeb6f9c-d23e-11e4-9241-2e0792a99d40.PNG): needs fix, edgy handles on top
  * [Article page](https://cloud.githubusercontent.com/assets/51007/6794962/2c3d96f4-d23e-11e4-942a-b8c9c2eaa5bd.PNG): works
* Pinterest
  * [Collection page](https://cloud.githubusercontent.com/assets/51007/6794983/6f769808-d23e-11e4-856a-1be2977f5c1a.PNG): needs fix, edgy handles on top
* QQ
  * [Home page](https://cloud.githubusercontent.com/assets/51007/6794988/7f3f9bf4-d23e-11e4-86bb-4244530a03a0.PNG): needs fix, edgy handles on top, right and bottom
  * [Article page](https://cloud.githubusercontent.com/assets/51007/6794989/7f876bd2-d23e-11e4-8c2d-6e02de7f5efa.PNG): works
* Taobao
  * [Home page](https://cloud.githubusercontent.com/assets/51007/6794998/9b2abcf4-d23e-11e4-9967-4618bd140d34.PNG): needs fix, edgy handles on left, top and right
  * [Product page](https://cloud.githubusercontent.com/assets/51007/6794997/9b2a1dbc-d23e-11e4-8629-4f86e6f971d1.PNG): needs fix, edgy handles on left, top and right
* Twitter
  * [Wall](https://cloud.githubusercontent.com/assets/51007/6794996/9b2904ea-d23e-11e4-8f54-2b3920cf5ba9.PNG): needs fix, edgy handles on left, top and bottom
* Wikipedia
  * [Home page](https://cloud.githubusercontent.com/assets/51007/6795002/9b50cc46-d23e-11e4-9886-4e7c2a6c217e.PNG): needs fix, edgy handles on bottom
  * [Article page](https://cloud.githubusercontent.com/assets/51007/6794999/9b2b6f5a-d23e-11e4-93d6-c341126835ff.PNG): needs fix, selection doesn’t sufficiently cover article title
* Wall Street Journal
  * [Home page](https://cloud.githubusercontent.com/assets/51007/6795001/9b4c5120-d23e-11e4-9888-2dd7f0f949a0.PNG): needs fix, edgy handles on left and top, selects masthead and navigation but not the articles
  * [Article page](https://cloud.githubusercontent.com/assets/51007/6795003/9b51991e-d23e-11e4-9235-4f56367b9fcf.PNG): works
* Yahoo
  * [Home page](https://cloud.githubusercontent.com/assets/51007/6795004/9bc9df46-d23e-11e4-8027-dbeb5dfe955c.PNG): failed, edgy handles on left, handles cannot be seen on top and right because the selection overshoots
  * [Article page](https://cloud.githubusercontent.com/assets/51007/6795000/9b4c21aa-d23e-11e4-8df7-4a806827f3f5.PNG): needs fix, edgy handles on all sides

**Comment by ianb** [comment]
We've removed autoselect
