### ISSUE TITLE
Page vibrates in Page shot

### ISSUE THREAD

**Issue by Shantanu323** [mozilla-services/pageshot#1857]
While using Firefox test pilot page shot , I found out that while browsing kickass.cd or Google homepage, the whole page goes vibrating while I move my mouse cursor. It also shows that that page has more space to load, but actually it doesn't.

STR:

1.Open Firefox Browser
2.Go to a website (e.g _https://google.com, https://kickass.cd_)
3.Click on Page Shot plugin to take screenshot

Expected result: Still page, easy to select page for taking screenshot.
Actual Result: Page keeps vibrating with movement of mouse.

I have reproduced this bug with Firefox 51.0a2 on Windows 7 (32-bit)

Build ID :  20161027004020
User Agent :    Mozilla/5.0 (Windows NT 6.1; rv:5.0) Gecko/20100101 Firefox/51.0

**Comment by fzzzy** [comment]
I have seen this in the past, but I have not seen it recently. Will try to reproduce again. Thanks for the report.

**Comment by SoftVision-CosminMuntean** [comment]
I can also reproduce this issue when hovering the elements from specific websites (www.google.com, Firefox homepage, www.bing.com or www.kickass.cd).
The page bounces when hovering some elements, because a vertical or a horizontal scroll bar appears and disappears.
This issue appeared when the "region" indicator was implemented. 

Here is a screen recording with the issue: https://goo.gl/VaUi0O.

**Comment by ianb** [comment]
Let's revisit this when #1725 lands
