### ISSUE TITLE
Shot restore issue

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/pageshot#1898]
Encounted on latest master:

STR: 
* Expire a shot
* choose to restore shot for 14 days
* set expiration for 10 minutes and save
* hit refresh

Expected: page refreshes with the shot still there

Actual:
![shot refresh bug](https://cloud.githubusercontent.com/assets/3323249/20005287/b96cba80-a291-11e6-94c4-bf39824ed830.gif)

**Comment by johngruen** [comment]
Note, I had to comment out the `this.socialMetadata()` method which seems to be causing #1898

**Comment by johngruen** [comment]
I think the bigger issue is that setting a shot to expire in one day changes to 18 hours (on local). Maybe this has to do with how we're generating time stamps?

**Comment by ianb** [comment]
I'm seeing this locally, but it seems like a case where the PostgreSQL timezone differs from the server timezone.  If you are moving around, this seems... possible?  I don't exactly understand PostgreSQL timezones either.

I specifically tried this on the live site and it's okay.  I'm closing because it's just a development issue and I don't really know the solution.
