### ISSUE TITLE
Update Test Pilot yaml file

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1988]
Flag it as "experiment content"

**Comment by fzzzy** [comment]
This issue should probably be in the Test Pilot repo since nothing will change in the page shot repo.

**Comment by ianb** [comment]
I put it here because we are responsible for getting this done

**Comment by pdehaan** [comment]
YAML in question: https://github.com/mozilla/testpilot/blob/master/content-src/experiments/page-shot.yaml

**Comment by pdehaan** [comment]
Possibly also want to retake this screenshot on the tour since the Share button now has different/new icons.

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/20414820/535e1772-ace9-11e6-8981-bed13823fe55.png)
&mdash; https://pageshot.net/AWOZCcqS4s6g1hbS/testpilot.dev.mozaws.net

**Comment by ianb** [comment]
Submitted in https://github.com/mozilla/testpilot/pull/1876

If we want to fix https://github.com/mozilla-services/pageshot/issues/1988#issuecomment-261421240 we should open a new ticket.  (But I don't think it's worth updating that screenshot.)
