### ISSUE TITLE
Handles are hard to see

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#199]
With the new lightbox selection, the handles to resize the selection are hard to see.  Because of CSS and opacity it's not easy to make them pop in the way I'd like.  Maybe they need to be opaque?  Creative ideas welcome.
![screen shot 2015-03-20 at 9 50 40 am](https://cloud.githubusercontent.com/assets/44390/6753789/9a1a35f2-cee6-11e4-825c-0f5802a95c74.png)

**Comment by brampitoyo** [comment]
Yes. I reckon the resize handles need to be opaque, even when there’s already a lightbox around it lightbox.

We can follow the style of the selection handle on shot view (issue #201). Except this time, we use a dark lightbox instead of a blue border. The blue square resize handles remain the same: rgb(50,163,255). No opacity.

![pageshot-lightbox](https://cloud.githubusercontent.com/assets/51007/6774152/10edc15c-d181-11e4-9834-4b25a4070ced.png)

**Comment by ianb** [comment]
For now, let's just make the handles opaque and blue and see how that feels.

**Comment by brampitoyo** [comment]
Sounds good. In my design, the handle is both blue-coloured and opaque.

**Comment by brampitoyo** [comment]
Handle specs, per bug #201:

![pageshot-highlight-selection-handle](https://cloud.githubusercontent.com/assets/51007/6724145/17f044ca-ce57-11e4-9698-7ee951798029.png)

* Border and selection handle colour: rgb(50,163,255)
* Inner colour: rgba(50,163,255,.25)
* Border width: 2px
* Selection handle width & height: 8×8px
