### ISSUE TITLE
Installing from dev server leads to error

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#2245]
If you install [via this link](https://pageshot.dev.mozaws.net/homepage/install-test-local.html) the add-on installs okay, but then when you actually try to save a selection there is an error.  This is what I get:

```
TypeError: aWindow is null  PrivateBrowsingUtils.jsm:48:5
```

There's no traceback, but the code points to:

```javascript
  privacyContextFromWindow: function pbu_privacyContextFromWindow(aWindow) {
    return aWindow.QueryInterface(Ci.nsIInterfaceRequestor)
                  .getInterface(Ci.nsIWebNavigation)
                  .QueryInterface(Ci.nsILoadContext);
  }
```

That's not super helpful, as clearly `privacyContextFromWindow()` is being called incorrectly, but without a traceback it's hard to tell where from.  It might be possible to 

I tested in Developer Edition, but I don't think that's related.  We could try to debug by putting in enough console.log's to narrow down where it's happening, but since we have to upload that makes it a little hard.  OTOH, code doesn't have to be committed to upload it to dev.

**Comment by SoftVision-CosminMuntean** [comment]
I have created a new Page Shot (v 5.2.3638) custom build and I got the same error after saving or canceling a selection. However the selection is successfully saved or dismissed. 
I have tested on latest Nightly (54.0a1) and latest Aurora (53.0a2) builds.

**Comment by ianb** [comment]
Given that, it's possible aWindow is null is a red herring.  But that leaves us without leads :(

**Comment by 6a68** [comment]
I think what's happening here is a bug in the WebExtension messaging code. It's triggered when the overlay content script's page is destroyed before the message is received, something like:

- The 'Save' button in the Page Shot overlay is clicked
- The selector content worker sends the `send-event`, `overlay-save-button` message 
- The webextension [message handler code](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/ExtensionParent.jsm#191) in Firefox assumes the sender tab exists, and it tries to convert the sender's window into a WebExtension tab object
  - The process of converting a window into a tab involves [checking if it's a private window]().
- Because the sender is gone (i.e., the overlay has been closed), when the sender's window is converted into a tab, we get that error thrown by `PrivateBrowsingUtils.jsm`

**This bug doesn't seem to hurt anything**, and we could probably hack around it by waiting a beat to dismiss the overlay (maybe a short `setTimeout`). Seems fairly low priority to me.

More details:

You can't pause execution before that error is thrown, but you _can_ generate a trace:

- First, have Page Shot installed from the dev server, in latest Nightly, with the Browser Toolbox open.
- Open any website 
- Click the page shot button
- Select some part of the page
- In the Browser Toolbox, open the debugger, search (top right input box) for PrivateBrowsingUtils, then set the debugger at line 48
- Switch to the browser window with a page shot selection, click 'Save'
- The `aWindow is null` error will be logged in the browser console
- Switch back to the debugger, then right click the stack of functions (a horizontal strip of tabs just above the debugger pane that holds source code), then choose 'Copy'
- You should get a trace like this:

pbu_privacyContextFromWindow@resource://gre/modules/PrivateBrowsingUtils.jsm:48:4
pbu_isWindowPrivate@resource://gre/modules/PrivateBrowsingUtils.jsm:28:11
isBrowserPrivate@resource://gre/modules/PrivateBrowsingUtils.jsm:42:13
get incognito@resource://gre/modules/ExtensionTabs.jsm:183:11
convert@resource://gre/modules/ExtensionTabs.jsm:468:6
getSender@chrome://browser/content/ext-tabs.js:42:19
receiveMessage@resource://gre/modules/ExtensionParent.jsm:191:6
_callHandlers/responses<@resource://gre/modules/MessageChannel.jsm:586:15
_callHandlers@resource://gre/modules/MessageChannel.jsm:584:20
_handleMessage/deferred.promise<@resource://gre/modules/MessageChannel.jsm:643:6
_handleMessage@resource://gre/modules/MessageChannel.jsm:640:23
receiveMessage@resource://gre/modules/MessageChannel.jsm:165:4

**Comment by ianb** [comment]
Good investigation!

There's a possibility that just delaying deactivate() could fix this.  I'm also suspicious about the overlay causing a change, as it's just a visual part of the experience, the actual content worker code remains in place (in fact there appears no way to get rid of the worker once it is attached).  It's possible that because the background page opens a new page due to one of these messages, things get weird from there.  If so then maybe using setTimeout around the tab opening would fix it.

Nevertheless, the `aWindow is null` probably isn't causing any problems, and isn't causing the original problem of the pageshot.dev.mozaws.net version of the add-on not working.

**Comment by 6a68** [comment]
I'm going to double check that this doesn't break saving shots on the dev server. If it doesn't, I'll move this out to the 'next tasks' milestone.

**Comment by 6a68** [comment]
Hmm.

When I install the addon from the dev server (link in description) and take a shot, all the network traffic indicates it succeeded. The original `aWindow is null` error is gone.

Oddly, I'm not able to view the shot; when I click 'My Shots', a `self.port is undefined` error is thrown by a call to a line that was [changed](https://github.com/mozilla-services/pageshot/commit/0a32a7d1d4265e40b0b350f2d4860f7ef713377c#diff-2851e2577edbeb9bd2706d1884e91c47L134) 10 days ago. (How exactly is the dev server built?)

At any rate, the issue here seems to have gone away. Closing.
