### ISSUE TITLE
Investigate Trailmeme

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#267]
[Trailmeme](http://web.archive.org/web/20120118172657/http://trailmeme.com/) is a now defunct tool for generating sets of information ([an article on it](http://readwrite.com/2009/12/06/memex_xerox_trailmeme)).  @SamPenrose has a contact there as well.

**Comment by brampitoyo** [comment]
The easiest way to imagine Trailmeme and its ilk (e.g. [Pearltrees](http://www.mind-mapping.org/images/L410-1.jpg) and [SpicyNodes](http://www.mind-mapping.org/images/L372-2.jpg)) is to imagine the bookmark as a series of links organised not by tags (a la Delicious) or folders, but by the order in which visitors should move through them.

Instead of saying “Here are all the links around vermiculture”, you say “Here’s a map of vermiculture. Start here, then follow the trail of branching subtopics and interconnecting links.”

It’s an interesting idea, with a few fundamental flaws:

1. Ordering many links into a map that tells a coherent story seems to be hard work. Who has the time to curate, assemble and annotate?
2. Once a map is created, it isn’t clear what one could do with it. Can you make it go viral? Probably not, because compared to a screenshot or a link, it takes time for visitors to go through all the links. Can you keep it as a mental note to yourself? Yes, but creating the map takes a lot of effort.
3. While visiting a link, the context isn’t displayed clearly. You can navigate to previous and next, but it’s hard to view the map and jump around. Even if you could view the map easily, it still doesn’t give you an idea of what the map is *about*. Each node is displayed as a page title rather than annotated with commentary of why the link is relevant.

**Comment by SamPenrose** [comment]
Hypothesis: we already have an abundance of ways to intentionally name and make trails. The opportunity is for light machine-learning to help us recall the trails we've followed without quite knowing it. For example, let's say I visited 50 pages in 2 hours one afternoon while researching topic X, while regularly checking updates on a sporting event and visiting some associated links from that. V0 of a new Memex would simply augment "Show All History" with manual clustering functionality -- in fact, maybe it exists as the "tags" column I just noticed on that page. V1 might do some simple automated clustering, based on link opening, tab switching, and textual analysis, and maybe at the same time allow manual editing of clusters. V2 could migrate clustering into about:newtab: for example, I open the same Etherpads before meetings each time. Why doesn't FF surface them in about:newtab when I invoke it at the weekly meeting time?

**Comment by brampitoyo** [comment]
I love your ideas. The new Memex will need to automate very hard tasks that have surprisingly intuitive description.

* Textual analysis
  * Look at page content that user visited
  * Discern what each page is about
* Timestamp and frequency of visits
  * Sites frequently vs. infrequently visited
  * Sites visited neither frequently nor infrequently, but always at a certain time of the day
* Tab switching and duration
  * Tabs that are kept open for a long time but not necessarily accessed
  * Tabs that are returned to again and again, or regularly

When we have this duration, then we can start clustering and figuring out what we think is important. Project Chronicle @johngruen might have many of the same ideas here.

**Comment by ianb** [comment]
Filed to [gdocs](https://docs.google.com/document/d/1KF1C6y_Qlh7-xuIxwC_zaK4sRLIkaQNQBDj0maEKpO0/edit)
