### ISSUE TITLE
Design text clip add button

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#313]
Right now it goes above the first line, like:

![screen shot 2015-04-20 at 1 42 36 pm](https://cloud.githubusercontent.com/assets/44390/7237741/1fdf945e-e763-11e4-9963-0f8a9f3d35a9.png)

That ain't right.  But I'm not exactly sure where it should go.  There are some conventions around the "tweet this selection" widgets that have become common (e.g., on Medium, NYTimes).

I think the features we want:

- Not too annoying, if you didn't want to make a clip
- Sticks out enough that you realize the button is there, even if you weren't expecting it (for discovery)
- Clearly relates to PageShot

**Comment by brampitoyo** [comment]
> Not too annoying, if you didn't want to make a clip

I don’t think this will be a problem. If the only way to show the add button is by first clicking on Pageshot, then we know for sure that user had wanted to make a clip instead of just highlighting a text.

Of course, then, there should be an easy way of dismissing the add button and return to the normal text selection behaviour. How do we do this?

**Comment by ianb** [comment]
No longer present
