### ISSUE TITLE
Design shot index page

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#384]
The homepage should show your shots in some reasonably nice format.  We should start out simple, but at least now we have the ability to query your shots so we can do something.

**Comment by brampitoyo** [comment]
I’ve been working on the home page today, so there’s going to be something to present at our meeting tomorrow. Stay tuned.

**Comment by brampitoyo** [comment]
The home page should list all the shots that user has taken, sorted by date. Ideally, it’ll have a URL that user can click in order to go to source, and a timestamp.

![pageshot-web-home-sort-by-date](https://cloud.githubusercontent.com/assets/51007/8000116/6bb1b9c8-0baa-11e5-9d3e-0f3233edcc44.PNG)

It can also sort by website. For instance, every page that the user has shot inside nytimes.com should be labeled either with the domain name (nytimes.com) or site name (New York Times).

Displaying name might be hard, as not every site has `<meta property="og:site_name">`. So perhaps we could utilise a hybrid approach and display `og:site_name` if possible, but revert to URL if impossible?

![pageshot-web-home-sort-by-website](https://cloud.githubusercontent.com/assets/51007/8000118/72e4ffe8-0baa-11e5-8e9c-f2992d029bac.PNG)

Clicking on the site name/URL or on “See all” will take user to the list of saved pages within that website. Quite self explanatory.

If we can display site name, the URL title up above could be replaced. For example, ‘theguardian.com’ becomes ‘The Guardian’.

![pageshot-web-website-listing-page](https://cloud.githubusercontent.com/assets/51007/8000139/e6ddbe8a-0baa-11e5-927c-fd58152b97b7.PNG)

**Comment by ianb** [comment]
Current design:

![screen shot 2015-07-28 at 5 32 45 pm](https://cloud.githubusercontent.com/assets/44390/8945626/aea86dc6-354e-11e5-991b-d24ae02848e3.png)

**Comment by brampitoyo** [comment]
Some inspiration from earlier designs:

#### Sort by domain

![pageshot-web-index-sort-by-domain](https://cloud.githubusercontent.com/assets/51007/8946264/277380e4-35e3-11e5-9106-0a9e0a0c5fa3.PNG)

#### Sort by date

![pageshot-web-index-sort-by-date](https://cloud.githubusercontent.com/assets/51007/8946267/2e845fe8-35e3-11e5-99e0-4d3fe942c750.PNG)

#### Sort by origin
(ie. Where the link originated from. Did you visit the link via Facebook? Via Twitter? Via your email client?)

![pageshot-web-index-sort-by-origin](https://cloud.githubusercontent.com/assets/51007/8946278/38b8e862-35e3-11e5-8815-ad7c5f26165e.PNG)

**Comment by ianb** [comment]
For first launch:

- Add date the shot was taken
- Use the favicon as a background, with a CSS fuzzy transform
- Make the items square
- Maybe put in comment bubble

**Comment by ianb** [comment]
Screenshot:
![screen shot 2015-11-09 at 10 04 20 pm](https://cloud.githubusercontent.com/assets/44390/11054174/190d9fa2-872e-11e5-810b-03f52aa4c44a.png)

**Comment by ianb** [comment]
Any followup work will happen in a different bug
