### ISSUE TITLE
Use consistent terminology

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#39]
A proposed description of what we have now:

**Shot** or **Shot Page**: what you make when you shoot a page, the web page that is created

**Full Page**: the frozen page, as framed in the full view

**Source page**: the page from which the shot was taken

**Clip**: an **image clip** or a **text clip**; an image click is a rectangle taken from the page.

**Viewer**: the person viewing the shot, who did not create the shot.

**Creator**: the person who made the shot

**Navigation bar**: the bar at the top of the page (that has the title, etc)

**Top bar**: the bar you get when you click the PageShot button, that lets you save the shot.

**My Shots**: the shot index page, where you can see all your devices.

**Comment by brampitoyo** [comment]
> Clip (?): an image clip or a text clip; an image click is a rectangle taken from the page, a text clip is some text (maybe markup?) taken from the page.

I prefer **clip** instead of **highlight** or **snippet**. I also like **select**, but a bit less. First of all, it makes the action (clipping an area of the page) distinct from the end product (a bunch of clippings comes together to make a highlights view).

Need names:
* The place where clips go in the border: yes, we called it **drawer**
* The clip that we use as the primary image: **cover image**?
* The person who made the shot: **poster** or **OP**. *Poster* is ambiguous, and *OP* makes it sound like a teenage Redditor, but they’re less formal. Like, who cares about the source? The poster took something that’s been posted somewhere else, that’s not theirs, and saved it.
* The person who is viewing the shot: **viewer** sounds good.
* The top part of the frame, where we put the controls: **toolbar**?
* Edit mode? I like either **selection mode** or **clipping mode**, with the action being **select** or **clip**. Keep in mind, like the above, that select is a more generic word than clip.

Still unsure:
* The draggable bits of a selection
* The automatically extracted information, things like an excerpt, microdata
* The content Readability identifies as interesting
* If there's any distinguishing features to the URL, e.g., deep links to a non-default view.
* The default view? What a viewer gets when they click on the link, be it full view or highlights. If we did something like pinning, the pinned view?
* The comment indicator in the collection view ("comment indicator" perhaps?)
* Any widgets we start to create

**Comment by ianb** [comment]
I find "poster" feels a little odd in context.  Like, "only the poster can add clips" – reads kind of ambiguously to me.  "OP" is too Reddit (or worse 4chan ;), and also to me implies that it's a shared thing that was just set off by the OP.  E.g., the OP of a Reddit post doesn't really own the post, they just started it (implied by "original" IMHO).  So... let's think about that one more.  (I'm implying by this that I expect the creator to "own" the shot, and for example can delete it.)

**Comment by ianb** [comment]
Original text updated with what we've said in these comments.

**Comment by ianb** [comment]
Last task is to find a place to put these descriptions (README or something)

**Comment by brampitoyo** [comment]
How about the repo wiki? Perhaps not obvious enough.

**Comment by ianb** [comment]
I'm not a fan of GitHub wikis, too easy to forget about.  Maybe CONTRIBUTING.md (which we should create anyway).

**Comment by ianb** [comment]
First comment is the current version.
