### ISSUE TITLE
Choose fonts

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#454]
We're just using sans-serif.  We should decide on fonts.  Probably stick with normal Firefox fonts though.

**Comment by brampitoyo** [comment]
Apparently, Mozilla uses `-moz-use-system-font` in its UI to make sure that it always uses whatever font that the OS specifies, rather than `sans-serif`.

I wonder if we can do this?

With sans-serif, either the value will change based on what you’ve selected in the Preferences, or it will default to Arial.

**Comment by ianb** [comment]
I tried `font-family: -moz-use-system-font` and it resulted in a serif font (presumably the whole thing wasn't recognized).  I'm not sure how it's supposed to work, though there are examples on Github that look like what I tried.

**Comment by brampitoyo** [comment]
Weird. You’d think that add-ons would use the same CSS that `browser.xul` is using.

Ideally, we’d like to use:
* `\.Helvetica Neue DeskInterface` on Mac
* `Segoe UI` on Windows Vista and above
* `MS Sans Serif` on Windows XP and below
* `Ubuntu` on Ubuntu
* `Dejavu Sans` on other Linux distros

But this would make the selector go crazy, so in this case, let’s just stick to `sans-serif`.

**Comment by ianb** [comment]
It might be that I'm just not using it properly.

**Comment by ianb** [comment]
This isn't very relevant to the interface now
