### ISSUE TITLE
addon/icons/library-empty.svg is white not black

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#463]
Should be black to match the PageShot button

**Comment by brampitoyo** [comment]
Updated in issue #189. You could also replace camera-empty.svg and camera-full.svg with the version found there because I had uploaded them with the incorrect colour last time.

* https://www.dropbox.com/s/z9l6knud0y5f2pc/camera-empty.svg
* https://www.dropbox.com/s/07mji289apfcx8a/camera-full.svg
* https://www.dropbox.com/s/78fdmm3cp1etozy/library-empty.svg
