### ISSUE TITLE
Integrate with Firefox Accounts

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#62]
Some more info [here](https://github.com/mozilla/fxa-oauth-server/wiki/How-do-I-integrate-with-Firefox-Accounts%3F#initiating-fxa-login-from-a-relying-service)

**Comment by brampitoyo** [comment]
**Adding name in doorhanger**

![pageshot-add-name-doorhanger](https://cloud.githubusercontent.com/assets/51007/7999233/3aeafda8-0b9c-11e5-91bd-924cce62a5c7.gif)

Note: name field appears only after you highlight comment field. Comment field only appears if you click ‘Edit’ on the Welcome panel.

**Adding name in web interface**

![pageshot-add-name-web](https://cloud.githubusercontent.com/assets/51007/7999249/6496a102-0b9c-11e5-9532-e644a4bbfa53.gif)

Self explanatory. User menu can be accessed from the navigation area up top.

Note: On Shot page, User menu is located to the right of Home button. But on Shot Listing page, User menu is on the right-hand corner of the screen. This is because, on Shot page, the right-hand corner is reserved for navigation arrows.

![pageshot-web-user-menu-placement](https://cloud.githubusercontent.com/assets/51007/7999312/2c7a8954-0b9d-11e5-81f0-b4fcd00019d7.PNG)
