### ISSUE TITLE
Design the "User's first shot" page

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#698]
It's in server/src/static/homepage/help.html (this is the page that is opened immediately after installation)

**Comment by brampitoyo** [comment]
The user’s first shot page is a page with many image thumbnails displayed side by side. This is not fancy, but intentional. Using these thumbnails, we can clearly demonstrate the difference between highlighting a specific part of the page versus saving the whole page DOM.

Demo video:
http://cl.ly/2i250i323d3K

HTML:
http://codepen.io/brampitoyo/pen/zvoQWm

What do you think?
