### ISSUE TITLE
Configurable expiration times on pages

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#729]
Even if we remove or adjust the 2 week expiration, allowing the user to give an expiration is probably a good idea.  Could be for a configurable amount of time.  pastebin for instance has this:

![screen shot 2015-09-02 at 5 41 13 pm](https://cloud.githubusercontent.com/assets/44390/9646503/da31c818-5199-11e5-96b8-3144fc034df7.png)

This still leaves me concerned about how well users will fill in this information, and what we want to default to.

**Comment by brampitoyo** [comment]
Here’s what a PageShot web page with configurable expiration control looks like.

![expire-ui-1](https://cloud.githubusercontent.com/assets/51007/10093035/69d0fe1c-63a1-11e5-9ac8-17116e8c128e.png)

You’ll note that a link called “Change” appears on the right of the expiration date. When you click on this link, the date text is replaced by a drop down menu, the link “Change” becomes “Save”, and a link called “Delete” appears to the right of “Save”.

![expire-ui-2](https://cloud.githubusercontent.com/assets/51007/10093098/f3e58ef6-63a1-11e5-939a-3262612cd8cd.png)

From this drop down menu, you can select any value you like. In this example, I’ve changed it to 2 weeks.

The time selected does not get added to initial value. For instance, if my expiration time is 15 hours and I changed it to 2 weeks, my new expiration time isn’t 2 weeks and 15 hours. It’s 2 weeks.

Through this interface, you’ll also get the option to delete the shot. Deleting a shot is the equivalent of making it expire right away (ie. the page gets replaced with a “The shot is no longer here. Here’s the URL to source instead”.

Why not put a drop down option called “Expired in [immediately]”? Because “Delete” is much clearer and more understandable.

![expire-ui-3](https://cloud.githubusercontent.com/assets/51007/10093146/96297a38-63a2-11e5-8795-bd9b043f2f38.png)

I’ve changed the expiration date to 2 weeks, and the new value shows. I can change it again, of course.

![expire-ui-4](https://cloud.githubusercontent.com/assets/51007/10093147/96542d14-63a2-11e5-8ebd-5b3d3b1b1b44.png)
