### ISSUE TITLE
Put in X button

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#997]
Per the [design](https://mozilla.invisionapp.com/share/GK5KN2O58#/screens/133080709):

![image](https://cloud.githubusercontent.com/assets/44390/13441435/bfb98aa0-dfbc-11e5-8262-0dc24fc63224.png)

It will act just like clicking the background (which will be fixed in #985), so it's mostly a visual hint.

We need an asset from @brampitoyo

**Comment by brampitoyo** [comment]
https://www.dropbox.com/s/na0lfgbmj7vbp5n/close.svg

Design spec:
Put in the middle of a 32x32 white circle.

I can generate the x within a circle, too, if you prefer.

**Comment by fzzzy** [comment]
Might be best if you just put the circle in there too.

**Comment by brampitoyo** [comment]
Check the dropbox link for updated asset.

**Comment by ianb** [comment]
We should discuss the placement of the X, it feels a little weird right now, I can't tell what it's intended to close.

**Comment by ianb** [comment]
Also we need `pointer:cursor` on the X

**Comment by brampitoyo** [comment]
The x button is positioned absolutely, 10 px from the top and 10 px from the right. This is to make it so that it will look nice on almost any window size (including narrow layout).

Keep in mind that you can click/tap anywhere to close.

I’ve thought of putting the x on the top-right corner of each clip. This is a standard behaviour. You’ll find it in almost every image zoom library out there. We can certainly do this, but this would mean that the button position will change depending on clip size, which is not ideal.

**Comment by ianb** [comment]
For reference, here's what it looks like currently:

![image](https://cloud.githubusercontent.com/assets/44390/13558718/42e3d032-e3cf-11e5-84a1-c3471ce8dbe9.png)

Something about how the X lines up with the framed/bordered page makes it feel odd to me.

**Comment by fzzzy** [comment]
We're going to darken the background, and remove the border around the saved full page if there is a clip. (If there is no clip, but only the full page is saved, we will keep the border)

**Comment by fzzzy** [comment]
Also, we might try removing the border even if the full page is saved with no clips, to see how it looks.

**Comment by fzzzy** [comment]
This was fixed in the cleanup I did last night. We got rid of the border around the framed page, making the association between the X and the full page less strong.
